### ISSUE TITLE
deepfake_detetction_test

### ISSUE THREAD

**Issue by njustczr** [vishal3477/Reverse_Engineering_GMs#1]
if i use the script, i just put the test data like this?
![image](https://user-images.githubusercontent.com/30426320/122734066-5958c900-d2b0-11eb-9c02-78928d32bcc6.png)

**Comment by vishal3477** [comment]
@njustczr, yes. That is correct.

**Comment by njustczr** [comment]
> @njustczr, yes. That is correct.

thanks, i also want to know if '0' is the fake image and '1' is the real image? and there are three weights in the deepfake_detection, is there any difference between them?

**Comment by vishal3477** [comment]
@njustczr , '0' is the fake image and '1' is the real image. Also, the pre-trained models are provided for the data the model is trained on. The folder name tells about the data.

**Comment by njustczr** [comment]
> @njustczr , '0' is the fake image and '1' is the real image. Also, the pre-trained models are provided for the data the model is trained on. The folder name tells about the data.

i mean in the deepfake detection folder, there are three  weights like the following image
![image](https://user-images.githubusercontent.com/30426320/123073487-09f9d080-d449-11eb-88cf-b32ef85d395c.png)

**Comment by vishal3477** [comment]
@njustczr , can you tell me the link you are accessing? Because, I'm seeing this from my end. 
![image](https://user-images.githubusercontent.com/54484274/123192981-f3b43a80-d471-11eb-8f0e-3f529cc4c100.png)

Can you try accessing the models using https://drive.google.com/drive/folders/1bzh9Pvr7L-NyQ2Mk-TBSlSq4TkMn2anB?usp=sharing ?

**Comment by njustczr** [comment]
> @njustczr , can you tell me the link you are accessing? Because, I'm seeing this from my end.
> ![image](https://user-images.githubusercontent.com/54484274/123192981-f3b43a80-d471-11eb-8f0e-3f529cc4c100.png)
> 
> Can you try accessing the models using https://drive.google.com/drive/folders/1bzh9Pvr7L-NyQ2Mk-TBSlSq4TkMn2anB?usp=sharing ?

Yes, we are the same.But i do not know what's the difference between 'uadfv', 'dfdc_uadfv' and 'dfdc'?

**Comment by vishal3477** [comment]
So uadfv is model trained on UADFV data, dfdc is model trained on DFDC data, and dfdc_uadfv is model trained on DFDC+UADFV data combined.

**Comment by njustczr** [comment]
> So uadfv is model trained on UADFV data, dfdc is model trained on DFDC data, and dfdc_uadfv is model trained on DFDC+UADFV data combined.

thanks
