### ISSUE TITLE
deepfake_detection.py gives an error ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

### ISSUE THREAD

**Issue by ssablak** [vishal3477/Reverse_Engineering_GMs#10]
@vishal3477 I couldn't run **fake_detection_test.py". It gives the following error below.
Thanks,

```python
optimizer.load_state_dict(state1['optimizer_1'])
```

![deepfake_detection_test_error](https://user-images.githubusercontent.com/12865778/126589473-9d9cd325-90d8-4e4c-9be1-fc7fafe8927d.png)

**Comment by ssablak** [comment]
@vishal3477 could you please help me with how to get the correct model file or fix the bug?

**Comment by vishal3477** [comment]
@ssablak can you try it again with the newer commit?

**Comment by ssablak** [comment]
@vishal3477 it works now. Thank you very much.
