### ISSUE TITLE
There is no codes about the cluster prediction about the discrete type network structure parameter in the encoder_rev_eng.py file

### ISSUE THREAD

**Issue by zhangtzq** [vishal3477/Reverse_Engineering_GMs#16]
I'm sorry to have bothered you. 
But I didn't find the code for discrete type network structure parameter clustering prediction in the encoder_rev_eng.py file of the original models folder or in the latest Reverse Engineering 2.0 code compressed file. However, your article states the clustering prediction about discrete type network structure parameters, which is important to the result. Looking forward to your reply.

**Comment by vishal3477** [comment]
I have updated the files with the networks. Please have a look. Thanks!!

**Comment by zhangtzq** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thank you very much for your reply. I tend to reproduce the code, but I find that the shape of the p_131_dim.npy is (115,16). Meanwhile, the total number of GMs in the three clusters C1, C2, C3 is 115. Besides, the number of the GMs used to calculate the weight of the loss is 116. So, which one is right?115 or 116? If it is 116, please let me know the final C1,C2,C3 and p_131_dim_npy. If it is 115, please let me know the final weights of the loss.
        Besides, I download the datasets from the initial version of the code, which contains 116 GMs data for training, and 15 GMs data for test. The datasets link in the version 2 of the code is not stable,  and it only contain the train folder, which only contains 100 GMs.And in the paper, it states that data for 104 GMs are used for training, and the rest data for 12 GMs are for test.Above all,which one is right about the dataset division?
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        12/5/2022 11:43
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            State ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [vishal3477/Reverse_Engineering_GMs] There is no codes about the cluster prediction about the discrete type network structure parameter in the encoder_rev_eng.py file (Issue #16)
        
      
    
  
  
I have updated the files with the networks. Please have a look. Thanks!!

**Comment by vishal3477** [comment]
Hi, thank you for your comment. So for the p_131_dim.npy, each column has value for one discrete variable (6 network arch, 10 loss func), and there are 131 rows for all GMs. 

For the data, the drive link has one folder with 116 GMs. You need to separate out the test GMs from it. You can see supplementary for which GMs to separate. Finally, you need to update the list N by including only the GM which is in training. This is basically the folder number in alphabetical order. I'm really sorry for the inconvenience caused. I'll automate this in future.

**Comment by zhangtzq** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thank you for your reply. I find that the states about the data is 116 GMs now. However, p_131_dim.npy contains only 115 rows, not 131. Could you please provide the file with 131 rows? Best wishes! 
            
        
    
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        12/7/2022 12:58
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            State ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [vishal3477/Reverse_Engineering_GMs] There is no codes about the cluster prediction about the discrete type network structure parameter in the encoder_rev_eng.py file (Issue #16)
        
      
    
  
  
Reopened #16.

**Comment by vishal3477** [comment]
I'm really sorry for putting you through all this inconvenience. We are preparing a third release of the code with more GMs (131, currently 116). However, that is still not ready and it got mixed up with 2.0 release. So basically, the code is updated and is released for one of the sets i.e. set 2 (see supplementary. ). The number of clusters has been updated from 3 to 11. Previously, the number of clusters was wrong due to the mix-up. The cluster ground truth and p value would rely on clusters formed, which would change if we change the training GMs. We have released these files for set 2 for your training/testing purposes. We evaluate on 4 sets to check the variability. We will release files for all four sets in few days. For now, please go ahead and download the updated 2.0 release having files for set 2. The net.npy and loss.npy should have shape (116,15) and (116,10). The rest of the files will have 104 rows. Please accept my sincerest apologies for the inconvenience caused. Let me know if you face anymore difficulties.
