### ISSUE TITLE
What is "ground_truth_dir" in "reverse_eng_test.py"?

### ISSUE THREAD

**Issue by Huang-yihao** [vishal3477/Reverse_Engineering_GMs#2]
I have downloaded the data and model. When I run the "reverse_eng_test.py" file, I find that I can not provide the below files. Could you please answer how can I get these files?  Thank you very much!

```
ground_truth_net_all=torch.from_numpy(np.load(opt.ground_truth_dir+ "ground_truth_net_arch_100_15dim.npy"))
ground_truth_loss_all=torch.from_numpy(np.load(opt.ground_truth_dir+ "ground_truth_loss_100_3dim.npy"))
ground_truth_loss_9_all=torch.from_numpy(np.load(opt.ground_truth_dir+ "ground_truth_loss_100_9dim.npy"))
```

**Comment by vishal3477** [comment]
These files are located in the main directory of repository.  So you can give ground_truth_dir as ". /"

PS: i just noticed that there is a difference in name. I'll make a change as soon as possible. Till then, you can provide the path to the 3 .npy files located in the main directory. These are the ground truth matrix files used in code.

**Comment by Huang-yihao** [comment]
Thank you very much!

**Comment by ssablak** [comment]
@vishal3477 I don't see new files in repo
