### ISSUE TITLE
Groundtruth Files Issue

### ISSUE THREAD

**Issue by ssablak** [vishal3477/Reverse_Engineering_GMs#5]
Hi Vishal,
Where can I download the following files?
I see three .npy files on the repo but the naming is not matching the exact files between repo and source code.

I changed the filename in repo below

FROM
ground_truth_loss_func_3dim_file.npy
ground_truth_loss_func_8dim_file.npy
ground_truth_net_arch_15dim_file.npy
![groundtruth2](https://user-images.githubusercontent.com/12865778/126232048-d325a7ad-2e6b-49bf-a2e3-f592b4ae046e.png)

TO below
ground_truth_loss_100_9dim.npy
ground_truth_net_arch_100_15dim.npy
ground_truth_loss_100_3dim.npy

![groundtruthfiles](https://user-images.githubusercontent.com/12865778/126231907-a9795cd1-b75a-474b-8503-ee6f417a118a.png)

But it didn't run through. It gives the following error

![error](https://user-images.githubusercontent.com/12865778/126232533-fcbb1a9f-2aba-4133-9d5e-0d18be1a70aa.png)

Thanks,
-Steve

**Comment by vishal3477** [comment]
Thanks for pointing it out. I have made a change. Can you please try again now?
