### ISSUE TITLE
torch.rfft is deprecated 

### ISSUE THREAD

**Issue by ssablak** [vishal3477/Reverse_Engineering_GMs#7]
@vishal3477  Since rfft is deprecated in the newer torch versions. It gives the following error. 
![rfft](https://user-images.githubusercontent.com/12865778/126517028-cc068802-64f3-4f70-bc1b-267045a4de7c.png)

I tried to fix it, but it starts to give an error as 
![rfft2error](https://user-images.githubusercontent.com/12865778/126517239-21f525c7-de33-43e5-9655-c8760c5ab3fd.png)

Could you please help me how to define rfft in the newer version of pytorch?
Thanks.
-Steve

**Comment by vishal3477** [comment]
Hi, 
I'm really sorry, the code was written for pytorch 1.5.0. I can try to write the rfft function for new version of pytorch but it may take a while. Till then, can you please try by downgrading your pytorch version. Thanks!

**Comment by vishal3477** [comment]
If your issue is solved, I'll close the issue.
