### ISSUE TITLE
NameError: name 'out9hL4' is not defined

### ISSUE THREAD

**Issue by ssablak** [vishal3477/Reverse_Engineering_GMs#8]
@vishal3477 It gives the following error. 

![out9hL4](https://user-images.githubusercontent.com/12865778/126529749-b80beb91-0dd6-43c6-b022-279eef621738.png)

**Comment by vishal3477** [comment]
There was a typo in variable. Could you please try again with the updated code?

**Comment by ssablak** [comment]
@vishal3477  now it complains as **NameError: name 'out9hL7' is not defined**

**Comment by ssablak** [comment]
I fixed the problem in **encoder_rev_eng.py" as below line

```python
return outn1, outn2 ,outn3, outn4, outn5, outn6, outn7, out3L1, out3L2, out3L3, outh9L1, outh9L2, outh9L3, outh9L4, outh9L5, outh9L6, outh9L7, outh9L8
```
